language: node_js
node_js:
 — “7”
script:
 — echo “Deploy!!”
 — polymer test
 — polymer build
install:
 — npm install -g firebase-tools
after_success:
 — firebase deploy — project disciply-integration — token $FIREBASE_TOKEN